### ISSUE TITLE
Needs updating to Swift 2.0

### ISSUE THREAD

**Issue by Inferis84** [ra1028/RAReorderableLayout#18]
Updating to XCode 7 means that this is no longer usable without running the auto migration tool.

**Comment by liuxuan30** [comment]
Xcode 7 has a converter to do ths job. You could use it. I did, and works fine so far.

**Comment by Whirlwind** [comment]
I hope you can upgrade this project, if you are free.

**Comment by ra1028** [comment]
@Inferis84 @liuxuan30 @Whirlwind 
https://github.com/ra1028/RAReorderableLayout/pull/17
Updated to support Swift 2.0 by @ekimia .
