### ISSUE TITLE
Needs updating to Swift 3.0

### ISSUE THREAD

**Issue by dimakomar** [ra1028/RAReorderableLayout#36]
Updating to XCode 8 means that this is no longer usable without running the auto migration tool.

**Comment by dimakomar** [comment]
https://github.com/ra1028/RAReorderableLayout/pull/37

**Comment by DesmondPang** [comment]
Same. Please update to Swift 3.0

**Comment by Den-Ree** [comment]
Yes! Please)

**Comment by ra1028** [comment]
Sorry for being late...
I released [swift3 supported version](https://cocoapods.org/pods/RAReorderableLayout).
