### ISSUE TITLE
Swift 3, problems with Delegate, DataSource 

### ISSUE THREAD

**Issue by Den-Ree** [ra1028/RAReorderableLayout#42]
I have error "use of undeclared type RAReorderableLayoutDelegate...., DataSource"
I think that we need to add 'open', but not sure.

**Comment by ra1028** [comment]
Thx for your report @Den-Ree !
I've release a [new version](https://github.com/ra1028/RAReorderableLayout/tree/0.6.1).
Please give it a try!

**Comment by Den-Ree** [comment]
@ra1028 thx you) now works)
